# Generated by Django 4.2.1 on 2023-05-13 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Normal'), ('D', 'Deluxe')], max_length=20)),
                ('number', models.IntegerField()),
                ('pricePerNight', models.IntegerField()),
                ('size', models.IntegerField()),
                ('maxOccupancy', models.IntegerField()),
                ('discountPercentage', models.IntegerField()),
                ('isAvailable', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('balcony', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
