# Generated by Django 4.2.1 on 2023-05-13 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0010_alter_room_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckIn', models.DateField()),
                ('Checkout', models.DateField()),
                ('SpecialRequest', models.TextField()),
                ('Cancelled', models.BooleanField(default=False)),
                ('PaymentID', models.CharField(blank=True, max_length=100, null=True)),
                ('TotalPrice', models.IntegerField(blank=True, null=True)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.room')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('aadhar_id', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
